# Site
title:              Jay White
bio:                'A few words about me.'
description:        "Here is a short description about me. Probably more than one sentence."
logo:               'assets/img/logo.png'
portrait:           'assets/img/portrait.png'
background:         'assets/img/placeholder-big.jpg'
locale:             en_US
url:                https://JayWhite2357.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         _sass
  style:            compressed
