# Site
title:              Jay White
bio:                'Teacher, Learner, Husband, Follower'
description:        "I teach math. I learn math. I love my wife. I follow Christ."
logo:               'assets/img/logo.png'
portrait:           'assets/img/portrait.jpg'
background:         'assets/img/background.jpg'
locale:             en_US
url:                https://JayWhite2357.github.io
future: true

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         _sass
  style:            compressed

exclude:
  - /assets/img/PermanentMarker-Regular.ttf
include:
  - /MaxBettiNumbers/_*
